### ISSUE TITLE
What is the purpose of adding Entities as a Link  

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/TrackableEntities.Core.Sample#2]
Trackable Entities NetStandard Library

Add a NetStandard class library called NetCoreSample.Entities
Install NuGet package: TrackableEntities.Common.Core -Pre
Add a reference to System.ComponentModel.DataAnnotations.
Link generated entities from the NetCoreSample.Entities.Generated project.
Right-click NetCoreSample.Entities project, select Add New Item
Nviate to the Generated entities project and select all .cs files except NorthwindSlim.cs.
From the Add button dropdown select Add As Link.
Build the project.

What is the purpose of Adding entities as Link?

****

**Comment by tonysneed** [comment]
Great question .. so this section has to do with [generating server-side entities](https://github.com/TrackableEntities/TrackableEntities.Core.Sample#server-side-generated-trackable-entities) for use with Trackable Entities.  You can create these classes yourself by hand, or you can generate them be reverse engineering model classes from an existing database.  Presently, the Entity Framework tooling does not support customization of generated classes, so in this sample I am using the legacy EF 6.x tools to do this, which require a .NET 4.5 class library with a reference to classic EF 6.x.  But rather than copying the entities into a .NET Standard class library, you can link to the generated classes in the .NET 4.5 class library, which means you don't have to copy the code from one project to another each time you re-generate the classes (for example when the database schema changes).

Your question is timely, however, because I am about to release an [extension](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars) to the EF Core tooling that allows customization of generated classes using [Handlebars](http://handlebarsjs.com/) templates.  I am going to see if the EF team is interesting in accepting a pull request to integrate my solution in the EF Core toolchain.  But either way, in a day or two I will finish the extension and revise the instructions in the sample to use the native extension I've built.  Linking still may be necessary, however, because the EF tooling only works with .NET Core apps and not a .NET Standard library.

**Comment by tonysneed** [comment]
The [Entity Framework Core Power Tools](https://github.com/ErikEJ/EFCorePowerTools) support generating entities in a separate .NET Standard class library, so adding as link is no longer necessary.
